### ISSUE TITLE
RANS3P module testing - Suspension benchmark

### ISSUE THREAD

**Issue by Giovanni-Cozzuto-1989** [erdc/proteus#597]
Suspension benchmark:
https://github.com/erdc/air-water-vv/tree/gcoz_porous/2d/sediment/suspension
Proteus version:
https://github.com/erdc/proteus/tree/gco_rans3p

There are some issues with ebqe_velocity variables.
@cekees @adimako @manuel-quezada

**Comment by Giovanni-Cozzuto-1989** [comment]
`... 
[       5] Attaching models to model pressureInitial
[       5]    Mass Conservation Error3.9344894869415204e-05
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
    runName + '_run_prof')
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    runName + '_run_prof')
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
    runName + '_run_prof')
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
    runName + '_run_prof')
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'
    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'
Closing remaining open files: tank4.h5...    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'
Closing remaining open files: tank3.h5...AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'
Closing remaining open files: tank7.h5...Closing remaining open files: tank5.h5... done
 done
 done
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
    runName + '_run_prof')
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
    runName + '_run_prof')
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'
    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'
Closing remaining open files: tank1.h5...Closing remaining open files: tank6.h5...Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
Traceback (most recent call last):
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/centos/bin/parun", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/scripts/parun", line 484, in <module>
 done
    runName + '_run_prof')
    runName + '_run_prof')
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/Profiling.py", line 190, in __call__
    return func(*func_args, **func_kwargs)
    return func(*func_args, **func_kwargs)
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
  File "/home/HR/gco/PROTEUS/proteus_add_rans3p/proteus/proteus/NumericalSolution.py", line 1117, in calculateSolution
 done
    lm.getResidual(lu,lr)
    lm.getResidual(lu,lr)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
  File "proteus/mprans/RANS3PSed.pyx", line 4102, in mprans.RANS3PSed.LevelModel.getResidual (proteus/mprans/RANS3PSed.cpp:54577)
AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'AttributeError: Coefficients instance has no attribute 'ebqe_velocity_last'

Closing remaining open files: Closing remaining open files: tank2.h5...tank0.h5... done
 done
 done
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[2379,1],2]
  Exit code:    1
--------------------------------------------------------------------------
`

**Comment by Giovanni-Cozzuto-1989** [comment]
I got an error with the latest version of master branch.
It's happening during the NAHeader Preconditioner SimpleNavierStokes step.
@alistairbntl do you have any idea of what is going on?
Am I missing something?

![immagine](https://user-images.githubusercontent.com/15638848/30803786-d5c5ce14-a1e2-11e7-8cba-875c03d94ea2.png)

**Comment by Giovanni-Cozzuto-1989** [comment]
@cekees this happens when I run in parallel with mpirun and either superlu_dist or asm.
When I use just parun I don't get this error.

**Comment by cekees** [comment]
Don't use SimpleNavierStokes2D on rans3p. Just set to None.
