### ISSUE TITLE
Hotstart Error

### ISSUE THREAD

**Issue by GAHubbard** [erdc/proteus#614]
Hello,

I'm getting the following error when trying to use hotstart. I have all *.py, mesh.*, and pesc_options files copied into the same directory as the output files from the previous run. Followed instructions from: 
https://github.com/erdc/proteus/wiki/How-To-Start-a-Run-From-Existing-Data-Files-%28%22Hot-starting%22%29

Additional Information:
Proteus commit 5f910f88239dd7fafd0bdfcb28521ddf60d924c3
Using benchmark case dambreak_Ubbink from air-water-vv, latest commit
Using command: parun dambreak_Ubbink_so.py -l 2 -v -O petsc_options -H

Any help is much appreciated.

Traceback (most recent call last): 
  File "/cavs/projects/proteus/proteus/linux2/bin/parun", line 6 ,in <module> exec(compile(open(__file__).read(), __file__, 'exec')) 
  File "/cavs/projects/proteus/proteus/scripts/parun", line 484, in <module> runName + '_run_prof') 
  File "/cavs/projects/proteus/proteus/proteus/Profiling.py", line 190, in __call__ 
    return func(*func_args, **func_kwargs) 
  File "/cavs/projects/proteus/proteus/proteus/NumericalSolution.py", line 1070, in calculateSolution 
    lm.u[cj].femSpace.readFunctionXdmf(self.ar[index],lm.u[cj],tCount) 
  File "/cavs/projects/proteus/proteus/proteus/FemTools.py", line 3625, in readFunctionXdmf 
    u.dof[:]=ar.hdfFile["/"+u.name+"_p"+`ar.comm.rank()`+"_t"+str(tCount)] 
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/cavs/projects/proteus/warhawk1-gcc-4.9/tmp/h5py-23ywhqphshet/h5py/_objects.c:3185) 
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/cavs/projects/proteus/warhawk1-gcc-4.9/tmp/h5py-23ywhqphshet/h5py/_objects.c:3143) 
  File "/cavs/projects/proteus/proteus/linux2/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__ 
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl) 
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/cavs/projects/proteus/warhawk1-gcc-4.9/tmp/h5py-23ywhqphshet/h5py/_objects.c:3185) 
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/cavs/projects/proteus/warhawk1-gcc-4.9/tmp/h5py-23ywhqphshet/h5py/_objects.c:3143) 
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/cavs/projects/proteus/warhawk1-gcc-4.9/tmp/h5py-23ywhqphshet/h5py/h5o.c:4079) 
KeyError: "Unable to open object (Object 'p_p0_t11' doesn't exist)"

**Comment by cekees** [comment]
I believe this was fixed in https://github.com/erdc/proteus/pull/606, which is was  merged into release 1.4.0 and is  in the master branch.  Let me know if you still have issues.

**Comment by adimako** [comment]
+1

**Comment by cekees** [comment]
Will reopen if we hear new reports of trouble.
